/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Esmeralda
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        JButton botonesH[] = {cmdCrear, cmdLimpiar};
        JButton botonesD[] = {cmdAutomatico, cmdManual, cmdOperacion};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmdOperacion = new javax.swing.JButton();
        cmdCrear = new javax.swing.JButton();
        cmdManual = new javax.swing.JButton();
        cmdAutomatico = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNoColumnas = new javax.swing.JTextField();
        txtNoFilas = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTablaResultado = new javax.swing.JTable();
        cmbOperaciones = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTablaInicial = new javax.swing.JTable();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("MATRICES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 140, 30));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 13), new java.awt.Color(102, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdOperacion.setBackground(new java.awt.Color(204, 255, 255));
        cmdOperacion.setFont(new java.awt.Font("Segoe Print", 1, 13)); // NOI18N
        cmdOperacion.setForeground(new java.awt.Color(51, 204, 0));
        cmdOperacion.setText("Operación");
        cmdOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOperacionActionPerformed(evt);
            }
        });
        jPanel2.add(cmdOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, 30));

        cmdCrear.setBackground(new java.awt.Color(204, 255, 255));
        cmdCrear.setFont(new java.awt.Font("Segoe Print", 1, 13)); // NOI18N
        cmdCrear.setForeground(new java.awt.Color(51, 204, 0));
        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        cmdManual.setBackground(new java.awt.Color(204, 255, 255));
        cmdManual.setFont(new java.awt.Font("Segoe Print", 1, 13)); // NOI18N
        cmdManual.setForeground(new java.awt.Color(51, 204, 0));
        cmdManual.setText("Manual");
        cmdManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdManualActionPerformed(evt);
            }
        });
        jPanel2.add(cmdManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 30));

        cmdAutomatico.setBackground(new java.awt.Color(204, 255, 255));
        cmdAutomatico.setFont(new java.awt.Font("Segoe Print", 1, 13)); // NOI18N
        cmdAutomatico.setForeground(new java.awt.Color(51, 204, 0));
        cmdAutomatico.setText("Automatico");
        cmdAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAutomaticoActionPerformed(evt);
            }
        });
        jPanel2.add(cmdAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, 30));

        cmdLimpiar.setBackground(new java.awt.Color(204, 255, 255));
        cmdLimpiar.setFont(new java.awt.Font("Segoe Print", 1, 13)); // NOI18N
        cmdLimpiar.setForeground(new java.awt.Color(51, 204, 0));
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 500, 80));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Iniciales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 13), new java.awt.Color(102, 0, 0))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 0));
        jLabel4.setText("No. de Filas:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 0));
        jLabel5.setText("No. de Columnas:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        txtNoColumnas.setBackground(new java.awt.Color(204, 255, 255));
        txtNoColumnas.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel3.add(txtNoColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 40, -1));

        txtNoFilas.setBackground(new java.awt.Color(204, 255, 255));
        txtNoFilas.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel3.add(txtNoFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 40, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 360, 70));

        tblTablaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblTablaResultado);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 390, 310));

        cmbOperaciones.setBackground(new java.awt.Color(204, 255, 255));
        cmbOperaciones.setFont(new java.awt.Font("Segoe Print", 1, 13)); // NOI18N
        cmbOperaciones.setForeground(new java.awt.Color(51, 204, 0));
        cmbOperaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Letra B", "Letra K", "Letra M", "Letra W", "Letra Q", "Letra J", "Letra G", "Letra R", "Figura1", "Figura2", "Figura3", "Figura4" }));
        jPanel1.add(cmbOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        tblTablaInicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblTablaInicial);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 390, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(935, 532));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int nf, nc;
        DefaultTableModel tm, tm2;

        if (txtNoFilas.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Digite el número de filas", 3);
            txtNoFilas.requestFocusInWindow();
        } else if (txtNoColumnas.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Digite el número de columnas", 3);
            txtNoColumnas.requestFocusInWindow();
        } else {

            nf = Integer.parseInt(txtNoFilas.getText());
            nc = Integer.parseInt(txtNoColumnas.getText());

            tm = (DefaultTableModel) tblTablaInicial.getModel();
            tm2 = (DefaultTableModel) tblTablaResultado.getModel();

            if (nf < 5 || nf > 16) {
                Helper.mensaje(this, "¡El número de filas debe ser mayor que 4 y menor que 17 para poder realizar las operaciones!", 3);
                txtNoFilas.requestFocusInWindow();
            } else if (nc < 5 || nc > 16) {
                Helper.mensaje(this, "¡El número de columnas debe ser mayor que 4 y menor que 17 para poder realizar las operaciones!", 3);
                txtNoColumnas.requestFocusInWindow();
            } else {

                tm.setRowCount(nf);
                tm.setColumnCount(nc);

                tm2.setRowCount(nf);
                tm2.setColumnCount(nc);

                JButton botonesH[] = {cmdAutomatico, cmdManual, cmdLimpiar};
                JButton botonesD[] = {cmdCrear, cmdOperacion};

                Helper.habilitarBotones(botonesH);
                Helper.deshabilitarBotones(botonesD);
            }
        }

    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdManualActionPerformed
        int nf, nc, n, sw, res;

        nc = tblTablaInicial.getColumnCount();
        nf = tblTablaInicial.getRowCount();

        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {

                do {
                    sw = 1;
                    try {
                        n = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el elmento en la posición [" + i + "] [" + j + "]").trim());
                        tblTablaResultado.setValueAt(n, i, j);
                    } catch (NumberFormatException e) {
                        Helper.mensaje(this, "Digite un número válido", 3);
                        sw = 0;
                    } catch (NullPointerException e) {
                        res = JOptionPane.showConfirmDialog(this, "¿Seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            sw = 1;
                            i = nf;
                            j = nc;

                            Helper.porDefectoTabla(tblTablaResultado);
                        } else {
                            sw = 0;
                        }
                    }
                } while (sw == 0);
            }
        }
        JButton botonesH[] = {cmdOperacion, cmdLimpiar};
        JButton botonesD[] = {cmdCrear, cmdManual, cmdAutomatico};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdManualActionPerformed

    private void cmdAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAutomaticoActionPerformed
        int nf, nc, n;

        nc = tblTablaInicial.getColumnCount();
        nf = tblTablaInicial.getRowCount();

        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
                n = (int) (Math.random() * 50 + 1);
                tblTablaInicial.setValueAt(n, i, j);
            }
        }
        JButton botonesH[] = {cmdOperacion, cmdLimpiar};
        JButton botonesD[] = {cmdCrear, cmdManual, cmdAutomatico};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdAutomaticoActionPerformed

    private void cmdOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOperacionActionPerformed
        int op, nf, nc;
        DefaultTableModel tm, tm2;

        op = cmbOperaciones.getSelectedIndex();

        nf = Integer.parseInt(txtNoFilas.getText());
        nc = Integer.parseInt(txtNoColumnas.getText());

        tm = (DefaultTableModel) tblTablaInicial.getModel();
        tm2 = (DefaultTableModel) tblTablaResultado.getModel();

        Helper.limpiarTabla(tblTablaResultado);

        switch (op) {
            case 0:
                Helper.letraB(tblTablaInicial, tblTablaResultado);
                break;

            case 1:
                if (nf < 7) {
                    Helper.mensaje(this, "El número de filas debe ser mayor a 7", 3);
                    txtNoFilas.requestFocusInWindow();
                } else if (nc < 7) {
                    Helper.mensaje(this, "El número de columnas debe ser mayor a 7", 3);
                    txtNoColumnas.requestFocusInWindow();
                } else {
                    Helper.letraK(tblTablaInicial, tblTablaResultado);
                }
                break;

            case 2:
                if (nf % 2 == 0) {
                    Helper.mensaje(this, "El número de filas debe ser impar!", 3);
                    txtNoFilas.requestFocusInWindow();
                } else if (nc % 2 == 0) {
                    Helper.mensaje(this, "El número de columnas debe ser impar!", 3);
                    txtNoColumnas.requestFocusInWindow();
                } else {
                    Helper.letraM(tblTablaInicial, tblTablaResultado);
                }
                break;

            case 3:
                if (nf % 2 == 0) {
                    Helper.mensaje(this, "El número de filas debe ser impar!", 3);
                    txtNoFilas.requestFocusInWindow();
                } else if (nc % 2 == 0) {
                    Helper.mensaje(this, "El número de columnas debe ser impar!", 3);
                    txtNoColumnas.requestFocusInWindow();
                } else {
                    Helper.letraW(tblTablaInicial, tblTablaResultado);
                }
                break;

            case 4:
                if (nf != nc) {
                    Helper.mensaje(this, "El número de filas debe ser igual al número de columnas!", 3);
                    txtNoFilas.requestFocusInWindow();
                } else {
                    Helper.letraQ(tblTablaInicial, tblTablaResultado);
                }
                break;

            case 5:
                Helper.letraJ(tblTablaInicial, tblTablaResultado);
                break;

            case 6:
                if (nf != nc) {
                    Helper.mensaje(this, "El número de filas debe ser igual al número de columnas!", 3);
                    txtNoFilas.requestFocusInWindow();
                } else {
                    Helper.letraG(tblTablaInicial, tblTablaResultado);
                }
                break;

            case 7:
                if (nf != nc) {
                    Helper.mensaje(this, "El número de filas debe ser igual al número de columnas!", 3);
                    txtNoFilas.requestFocusInWindow();
                } else {
                    Helper.letraR(tblTablaInicial, tblTablaResultado);
                }
                break;

            case 8:
                if (nf != nc) {
                    Helper.mensaje(this, "El número de filas debe ser igual al número de columnas!", 3);
                    txtNoFilas.requestFocusInWindow();
                } else if (nf % 2 == 0) {
                    Helper.mensaje(this, "El número de filas debe ser impar!", 3);
                    txtNoFilas.requestFocusInWindow();
                } else if (nc % 2 == 0) {
                    Helper.mensaje(this, "El número de columnas debe ser impar!", 3);
                    txtNoColumnas.requestFocusInWindow();
                } else {
                    Helper.Figura1(tblTablaInicial, tblTablaResultado);
                }
                break;

            case 9:
                if (nf != nc) {
                    Helper.mensaje(this, "El número de filas debe ser igual al número de columnas!", 3);
                    txtNoFilas.requestFocusInWindow();
                } else {
                    Helper.Figura2(tblTablaInicial, tblTablaResultado);
                }
                break;

            case 10:
                if (nf % 2 != 0) {
                    Helper.mensaje(this, "El número de filas debe ser par!", 3);
                    txtNoFilas.requestFocusInWindow();
                } else if (nc % 2 != 0) {
                    Helper.mensaje(this, "El número de columnas debe ser par!", 3);
                    txtNoColumnas.requestFocusInWindow();
                } else {
                Helper.Figura3(tblTablaInicial, tblTablaResultado);
                }
                break;

            case 11:
                if (nf != nc) {
                    Helper.mensaje(this, "El número de filas debe ser igual al número de columnas!", 3);
                    txtNoFilas.requestFocusInWindow();
                } else if (nf % 2 == 0) {
                    Helper.mensaje(this, "El número de filas debe ser impar!", 3);
                    txtNoFilas.requestFocusInWindow();
                } else if (nc % 2 == 0) {
                    Helper.mensaje(this, "El número de columnas debe ser impar!", 3);
                    txtNoColumnas.requestFocusInWindow();
                } else {
                Helper.Figura4(tblTablaInicial, tblTablaResultado);
                }
                break;
        }

        JButton botonesH[] = {cmdOperacion, cmdLimpiar};
        JButton botonesD[] = {cmdCrear, cmdManual, cmdAutomatico};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdOperacionActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtNoFilas.setText("");
        txtNoColumnas.setText("");
        txtNoFilas.requestFocusInWindow();
        cmbOperaciones.setSelectedIndex(0);

        Helper.porDefectoTabla(tblTablaInicial);
        Helper.porDefectoTabla(tblTablaResultado);

        JButton botonesH[] = {cmdCrear, cmdLimpiar};
        JButton botonesD[] = {cmdAutomatico, cmdManual, cmdOperacion};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperaciones;
    private javax.swing.JButton cmdAutomatico;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdManual;
    private javax.swing.JButton cmdOperacion;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblTablaInicial;
    private javax.swing.JTable tblTablaResultado;
    private javax.swing.JTextField txtNoColumnas;
    private javax.swing.JTextField txtNoFilas;
    // End of variables declaration//GEN-END:variables
}
